// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBik55rRqbSdzMF_r7VO9sNjOeLSXVjMaQ',
    appId: '1:496989429888:web:d903826f958fe7cf4e8665',
    messagingSenderId: '496989429888',
    projectId: 'flutterjikan',
    authDomain: 'flutterjikan.firebaseapp.com',
    storageBucket: 'flutterjikan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2y1RkY2fRF0FFGXwQdFMjTJjKc21wIY',
    appId: '1:496989429888:android:11e0881dbc46bf3d4e8665',
    messagingSenderId: '496989429888',
    projectId: 'flutterjikan',
    storageBucket: 'flutterjikan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBurlRJlUZjbllHQvQHHrvA5N32iEALkHw',
    appId: '1:496989429888:ios:f7f545a96bb80b374e8665',
    messagingSenderId: '496989429888',
    projectId: 'flutterjikan',
    storageBucket: 'flutterjikan.appspot.com',
    iosClientId: '496989429888-rngs8p4tte3es8fpqtfe9pch2588mblu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJikan',
  );
}
